# Base image
FROM node:13.12.0-alpine

# Set working directory
WORKDIR /setlist-frontend

# Add app code
COPY . .

# Install app dependencies
RUN npm install

# Port
EXPOSE $PORT

# Start the app
CMD ["npm", "start"]
