version: '3.4'
services:
  db:
    image: postgres
    env_file: ./backend/postgres.env
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
  api:
    build: ./backend
    env_file: ./backend/production.env
    ports:
      - "3000:3000"
    depends_on:
      - db
  ui:
    build: ./frontend
    stdin_open: true  # Required due to a bug in react-scripts 3.4.1
    ports:
      - "3001:3000"
    depends_on:
      - api
