version: "3.4"

services:
  
  db:
    image: postgres
    env_file: ./backend/postgres.env
  
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    depends_on:
      - db

  ui:
    build: 
      context: ./frontend
    stdin_open: true  # Required due to a bug in react-scripts v3.4.1
    depends_on:
      - api
