version: "3.4"

services:
  
  db:
    image: postgres
    env_file: ./backend/postgres.env
  
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - db

  ui:
    stdin_open: true  # Required due to a bug in react-scripts v3.4.1
    ports:
      - "3001:3000"
    depends_on:
      - api
