version: '3.4'
services:
  db:
    image: postgres
    env_file: postgres.env
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build: .
    env_file: production.env
    ports:
      - "3000:3000"
    depends_on:
      - db
